### ISSUE TITLE
Direct Messages Button?

### ISSUE THREAD

**Issue by TheHeroBilly** [cosmicsalad/Discord-Themes-and-Plugins#20]
I want to edit the button a little bit for my clan, where can I find the code for this button? (BTW Awesome theme)

**Comment by cosmicsalad** [comment]
✌🏼 Thanks! Well I'm going to be working on a new version in the next week or so that will make the theme a bit more modular and update for the latest discord changes. So you might have to change it back if you don't add this into Custom CSS, but look for '.guilds-wrapper .guilds .friends-icon:after' and edit the 'background-image: url' to change it for now. :)

**Comment by LWTechGaming** [comment]
@cosmicsalad Updating ASAP would make sense, there's currently a problem that affects quite a few themes where the background doesn't display. Tested with 2 different themes and neither got background images loaded which leads me to believe there's been a crucial change somewhere 🤔

**Comment by cosmicsalad** [comment]
@LWTechGaming Just pushed a big update with fixes! Let me know if I'm missing anything.

**Comment by LWTechGaming** [comment]
I'll check it out when I can, cheers :+1:
